# conda env create -f environment.yml

name: emg2pose
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.10.13
  - pytorch::pytorch==2.3.1
  - pytorch-lightning==2.2.2
  - numpy==1.26.4
  - scipy==1.13.1
  - h5py==3.11.0
  - unidecode==1.3.8
  - pandas==2.2.2
  - pyyaml==6.0.1
  - pytest==8.2.2
  - click==8.1.7
  - pre-commit==3.7.1
  - black==24.4.2
  - flake8==7.0.0
  - mypy==1.10.0
  - pip==24.0
  - trio==0.25.1
  - hydra-core==1.3.2
  - ffmpeg==7.1.0
  - pip:
    - plotly==5.24.1
    - av==13.1.0
    - opencv-python==4.10.0.84
    - pillow==11.0.0
    - kaleido==0.2.1
    - matplotlib==3.9.2
    - mediapy==1.2.2
    - joblib==1.4.2
    - nbformat==5.10.4
    - transformers==4.45.2
