# @package _global_
to_tensor:
  _target_: emg2pose.transforms.ExtractToTensor
  field: emg
  
selected_channels:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 11
  - 13

transforms:
  train:
    - ${to_tensor}
    - _target_: emg2pose.transforms.RotationAugmentation
    - _target_: emg2pose.transforms.ChannelSelect
      indices: ${selected_channels}
  val:
    - ${to_tensor}
    - _target_: emg2pose.transforms.ChannelSelect
      indices: ${selected_channels}
  test: ${transforms.val}
