defaults:
  - _self_
  - datamodule: default
  - optimizer: adamw
  - lr_scheduler: cosine
  - data_split: full_split
  - transforms: rotation_augmentation
  - experiment: last_step_xattn/small

data_location: /home/xiziheng/develop/emg2pose/data/emg2pose_data

seed: 42
matmul_precision: null  # one of: highest, high, medium

batch_size: 320
num_workers: 16  # Number of workers for dataloading

train: True  # Whether to run training
eval: True  # Whether to run evaluation on validation and test splits
checkpoint: null

monitor_metric: val_loss
monitor_mode: min

loss_weights:
  mae: 1
  fingertip_distance: 0.01

trainer:
  max_epochs: 200
  devices: [0]
  log_every_n_steps: 1
  strategy: ddp_find_unused_parameters_true
  precision: 32

# Evaluation-time option: slice preds/targets/masks to last timestep (for fair
# comparison with last-step models). Default False.
eval_last_only: true

# By default: static learning rate
callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    save_top_k: 3
    save_last: True
    verbose: True
    filename: "best-{monitor_metric:.4f}"
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    patience: 100
    check_on_train_epoch_end: False
    verbose: True

# Customize hydra directory outputs
# see: https://hydra.cc/docs/0.11/configure_hydra/workdir/
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}/seed=${seed}
  output_subdir: hydra_configs
  job:
    name: emg2pose
    config:
      override_dirname:
        exclude_keys:
          - seed
