defaults:
  - _self_
  - datamodule: cached
  - optimizer: adam
  - lr_scheduler: cosine
  - data_split: full_split
  - transforms: rotation_augmentation
  - experiment: regression_vemg2pose

data_location: /home/xiziheng/develop/emg2pose/data/emg2pose_data

seed: 42

batch_size: 32
num_workers: 4  # Number of workers for dataloading

train: True  # Whether to run training
eval: True  # Whether to run evaluation on validation and test splits
# checkpoint: /home/xiziheng/develop/emg2pose/logs/2025-10-31/22-39-59/lightning_logs/version_0/checkpoints/last.ckpt  # Optional path to checkpoint file
# checkpoint: /home/xiziheng/develop/emg2pose/emg2pose_model_checkpoints/regression_vemg2pose.ckpt
checkpoint: null

monitor_metric: val_loss
monitor_mode: min

loss_weights:
  mae: 1
  fingertip_distance: 0.01

trainer:
  max_epochs: 200
  devices: [5]
  log_every_n_steps: 20

# By default: static learning rate
callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    save_top_k: 3
    save_last: True
    verbose: True
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    patience: 50
    check_on_train_epoch_end: False
    verbose: True

# Customize hydra directory outputs
# see: https://hydra.cc/docs/0.11/configure_hydra/workdir/
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}/seed=${seed}
  output_subdir: hydra_configs
  job:
    name: emg2pose
    config:
      override_dirname:
        exclude_keys:
          - seed
